'use strict';
 
exports.BattleScripts = {
    init: function() {
        var abilityToItem = {
            aerilate: 'airballoon',
            adaptability: 'apicotberry',
            anticipation: 'blackbelt',
            arenatrap: 'buggem',
            aromaveil: 'blackglasses',
            aurabreak: 'blacksludge',
            baddreams: 'brightpowder',
            battlearmor: 'cellbattery',
            bigpecks: 'charcoal',
            blaze: 'chartiberry',
            bulletproof: 'chestoberry',
            cheekpouch: 'chilanberry',
            chlorophyll: 'chopleberry',
            clearbody: 'cobaberry',
            cloudnine: 'colburberry',
            colorchange: 'custapberry',
            competitive: 'damprock',
            compoundeyes: 'dragonfang',
            contrary: 'darkgem',
            cursedbody: 'ejectbutton',
            cutecharm: 'expertbelt',
            damp: 'flameorb',
            darkaura: 'focusband',
            defeatist: 'fullincense',
            defiant: 'ganlonberry',
            deltastream: 'grepaberry',
            desolateland: 'gripclaw',
            download: 'habanberry',
            drizzle: 'hardstone',
            drought: 'heatrock',
            dryskin: 'iapapaberry',
            earlybird: 'icyrock',
            effectspore: 'kasibberry',
            fairyaura: 'kebiaberry',
            filter: 'keeberry',
            flamebody: 'kelpsyberry',
            flareboost: 'kingsrock',
            flashfire: 'laggingtail',
            flowergift: 'lansatberry',
            flowerveil: 'laxincense',
            forecast: 'leppaberry',
            forewarn: 'liechiberry',
            friendguard: 'luminousmoss',
            frisk: 'magnet',
            furcoat: 'dragongem',
            galewings: 'marangaberry',
            gluttony: 'metalcoat',
            gooey: 'metronome',
            grasspelt: 'micleberry',
            guts: 'miracleseed',
            harvest: 'muscleband',
            healer: 'mysticwater',
            heatproof: 'nevermeltice',
            heavymetal: 'occaberry',
            honeygather: 'oddincense',
            hugepower: 'electricgem',
            hustle: 'passhoberry',
            hydration: 'payapaberry',
            hypercutter: 'petayaberry',
            icebody: 'poisonbarb',
            illuminate: 'quickclaw',
            illusion: 'razorclaw',
            immunity: 'razorfang',
            imposter: 'fairygem',
            infiltrator: 'rindoberry',
            innerfocus: 'rockincense',
            insomnia: 'roseincense',
            intimidate: 'redcard',
            ironbarbs: 'roseliberry',
            ironfist: 'safetygoggles',
            justified: 'salacberry',
            keeneye: 'scopelens',
            klutz: 'seaincense',
            leafguard: 'sharpbeak',
            levitate: 'shedshell',
            lightmetal: 'shellbell',
            lightningrod: 'shucaberry',
            limber: 'silkscarf',
            liquidooze: 'silverpowder',
            magicbounce: 'smoothrock',
            magicguard: 'snowball',
            magician: 'softsand',
            magmaarmor: 'spelltag',
            magnetpull: 'starfberry',
            marvelscale: 'stickybarb',
            megalauncher: 'tangaberry',
            minus: 'twistedspoon',
            moldbreaker: 'wacanberry',
            moody: 'waveincense',
            motordrive: 'weaknesspolicy',
            moxie: 'whiteherb',
            multiscale: 'widelens',
            multitype: 'wiseglasses',
            mummy: 'yacheberry',
            naturalcure: 'zoomlens',
            noguard: 'adamantorb',
            normalize: 'burndrive',
            oblivious: 'chilldrive',
            overcoat: 'deepseascale',
            overgrow: 'deepseatooth',
            owntempo: 'dousedrive',
            parentalbond: 'firegem',
            pickpocket: 'lightball',
            pickup: 'luckypunch',
            pixilate: 'griseousorb',
            plus: 'lustrousorb',
            poisonheal: 'metalpowder',
            poisonpoint: 'quickpowder',
            poisontouch: 'shockdrive',
            prankster: 'souldew',
            pressure: 'stick',
            primordialsea: 'thickclub',
            protean: 'aguavberry',
            purepower: 'icegem',
            quickfeet: 'aspearberry',
            raindish: 'bindingband',
            rattled: 'cheriberry',
            reckless: 'destinyknot',
            refrigerate: 'enigmaberry',
            regenerator: 'figyberry',
            rivalry: 'floatstone',
            rockhead: 'ironball',
            roughskin: 'jabocaberry',
            runaway: 'machobrace',
            sandforce: 'magoberry',
            sandrush: 'oranberry',
            sandstream: 'pechaberry',
            sandveil: 'persimberry',
            sapsipper: 'rawstberry',
            scrappy: 'ringtarget',
            serenegrace: 'rowapberry',
            shadowtag: 'poisongem',
            shedskin: 'wikiberry',
            sheerforce: 'armorfossil',
            shellarmor: 'belueberry',
            shielddust: 'blukberry',
            simple: 'psychicgem',
            skilllink: 'cherishball',
            slowstart: 'clawfossil',
            sniper: 'cornnberry',
            snowcloak: 'coverfossil',
            snowwarning: 'diveball',
            solarpower: 'domefossil',
            solidrock: 'dreamball',
            soundproof: 'durinberry',
            speedboost: 'duskball',
            stall: 'electirizer',
            stancechange: 'energypowder',
            static: 'fastball',
            steadfast: 'friendball',
            stench: 'greatball',
            stickyhold: 'healball',
            stormdrain: 'heavyball',
            strongjaw: 'helixfossil',
            sturdy: 'hondewberry',
            suctioncups: 'levelball',
            superluck: 'loveball',
            swarm: 'lureball',
            sweetveil: 'luxuryball',
            swiftswim: 'magostberry',
            symbiosis: 'masterball',
            synchronize: 'moonball',
            tangledfeet: 'nanabberry',
            technician: 'nestball',
            telepathy: 'netball',
            teravolt: 'nomelberry',
            thickfat: 'oldamber',
            tintedlens: 'pamtreberry',
            torrent: 'parkball',
            toughclaws: 'pinapberry',
            toxicboost: 'plumefossil',
            trace: 'pokeball',
            truant: 'pomegberry',
            turboblaze: 'premierball',
            unaware: 'qualotberry',
            unburden: 'quickball',
            unnerve: 'rabutaberry',
            victorystar: 'rarebone',
            vitalspirit: 'razzberry',
            voltabsorb: 'repeatball',
            waterabsorb: 'rootfossil',
            waterveil: 'safariball',
            weakarmor: 'skullfossil',
            whitesmoke: 'spelonberry',
            wonderguard: 'steelgem',
            wonderskin: 'sportball',
            zenmode: 'tamatoberry',
        }
        var largeArray = Object.getOwnPropertyNames(abilityToItem);
        for (var z = 0; z < largeArray.length; z++) {
            var currAbility = largeArray[z];
            var currItem = abilityToItem[currAbility];
            var itemArray = Object.getOwnPropertyNames(this.getItem(currItem));
            for (var i = 0; i < itemArray.length; i++) {
                var current = itemArray[i];
                var keepThese = ["id", "name", "spritenum", "num", "gen", "desc", "exists"];
                if (keepThese.indexOf(current) < 0) {
                    if (typeof this.getItem(currItem)[current] === "function") {
                        this.modData('Items', currItem)[current] = function(){return};
                        //otherwise stuff breaks
                    } else if (current === "isBerry" || current === "isUnreleased" || current === "isGem") {
                        this.modData('Items', currItem)[current] = false;
                        //just a precaution
                    } else if (current === "onNegateImmunity") {
                        this.modData('Items', currItem)[current] = true;
                        //for Ring Target
                    } else {
                        this.modData('Items', currItem)[current] = '';
                    }
                }      
            }
            console.log(currItem + " " + currAbility);
            this.modData('Items', currItem).enchanted = currAbility;
            var abilityArray = Object.getOwnPropertyNames(this.getAbility(currAbility));
            for (var j = 0; j < abilityArray.length; j++) {
                var current = abilityArray[j];
                var dontKeepThese = ["desc", "shortDesc", "id", "name", "num"];
                if (dontKeepThese.indexOf(current) < 0) {
                    this.modData('Items', currItem)[current] = this.getAbility(currAbility)[current];
                }
            }
            this.modData('Items', currItem).onTakeItem = function (pokemon) { return false };
        }
    },
}
